# Generated by Django 5.1.4 on 2025-02-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselling", "0002_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="counsellor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="counselling.counsellor",
            ),
        ),
    ]
