# Generated by Django 5.1.4 on 2025-03-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0004_rename_session_counsellingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellingsession',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='counselling.slot'),
        ),
    ]
