# Generated by Django 5.1.4 on 2025-02-06 04:24

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="transaction",
            managers=[
                ("objectrs", django.db.models.manager.Manager()),
            ],
        ),
    ]
