# Generated by Django 5.1.4 on 2025-02-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
    ]
