# Generated by Django 5.1.4 on 2025-02-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_channel',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
