# Generated by Django 5.1.4 on 2025-06-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_online_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='online_channel',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
