# Generated by Django 5.1.4 on 2025-07-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_online_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online_channel',
        ),
        migrations.AddField(
            model_name='user',
            name='active_devices',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
    ]
